services:
  namecheap:
    image: enayet123/namecheap-dyndns:latest
    container_name: namecheap
    restart: unless-stopped
    environment:
      - DOMAIN=your.domain.com
      - DYNAMIC_DNS_PASSWORD=password
      - SUBDOMAINS=subdomain,portal,admin
      - CHECK_INTERVAL_SECONDS=3600
